version: "3"

networks:
  backend:
    external: true

services:
  nuxt:
    build: ./
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend
    command: npm run start
